### ISSUE TITLE
Run as a phar

### ISSUE THREAD

**Issue by BackEndTea** [BackEndTea/PHP-Optimize#2]
A phar should be made, for users who prefer to run it like that.

Requires  #1

**Comment by Lucky-Loek** [comment]
I have some time in the next couple of days, so I can do this if you want.

**Comment by BackEndTea** [comment]
That would be great, though i'm not sure if its possible without implementing #1 first. Since the of the phar would be to run it as a command-line tool

**Comment by Lucky-Loek** [comment]
Yeah, I'll work that one out too. Shouldn't be too hard.
